-- Migration number: 0001 	 2025-07-12T04:18:57.038Z

CREATE TABLE User (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  bio TEXT, -- optional
  profileImageUrl TEXT, -- optional
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE (username)
);

CREATE TABLE Auth (
  userId INTEGER PRIMARY KEY,
  email TEXT NOT NULL,
  passwordHash TEXT NOT NULL,

  UNIQUE (email),
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE Article (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId INTEGER NOT NULL,
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  body TEXT NOT NULL,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE (slug),
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE INDEX idx_article_userId ON Article(userId);

CREATE TABLE Tag (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

  UNIQUE (name)
);

CREATE TABLE ArticleTag (
  articleId INTEGER NOT NULL,
  tagId INTEGER NOT NULL,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (articleId, tagId),
  FOREIGN KEY (articleId) REFERENCES Article(id) ON DELETE CASCADE,
  FOREIGN KEY (tagId) REFERENCES Tag(id) ON DELETE CASCADE
);

CREATE TABLE Comment (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  articleId INTEGER NOT NULL,
  userId INTEGER NOT NULL,
  body TEXT NOT NULL,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (articleId) REFERENCES Article(id) ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE INDEX idx_comment_articleId ON Comment(articleId);

CREATE TABLE Favorite (
  userId INTEGER NOT NULL,
  articleId INTEGER NOT NULL,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (userId, articleId),
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (articleId) REFERENCES Article(id) ON DELETE CASCADE
);

CREATE TABLE Follow (
  followerId INTEGER NOT NULL,
  followeeId INTEGER NOT NULL,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (followerId, followeeId),
  FOREIGN KEY (followerId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (followeeId) REFERENCES User(id) ON DELETE CASCADE
);
